### PR TITLE
Hardcoded file paths instead of using .env

### PR DESCRIPTION
**Pull request by ctlai95**
Changing this since I realized there's no point in having these as environment variables, and repo secrets are meant to be encrypted for api keys and things like that.

### CODE REVIEW

**Comment by henrytran28** [comment]
But then the hackers would know how much money chicken fried rice is...

**Comment by ctlai95** [comment]
> [firebase.google.com/docs/web/setup](https://firebase.google.com/docs/web/setup)
> 
> I would just leave the config alone. Doesn't hurt to have it as all security is done through permissions. If you read the Firebase config object section it mentions to not modify or remove key parts of the config.
> 
> I think its safe to remove the database url etc, but here are the minimum requirements:
> Firebase config files and objects section in [firebase.google.com/docs/projects/learn-more#config-files-objects](https://firebase.google.com/docs/projects/learn-more#config-files-objects)

Hmm okay I can revert it. Seems strange that I can remove all of those fields but still have it working.

**Comment by henrytran28** [comment]
Yeah not too sure... I'm reviewing in bed on my phone right now lol. You might be right in not needing it. I'm assuming you restarted the app too? What happens if you don't provide anything at all?

**Comment by ctlai95** [comment]
Yeah I restarted. My guess is that the warning on their docs only applies if we extend the app to use other firebase features maybe? If I don't provide anything it crashes.

**Pull request merged**
